
version: 2

models:
  - name: test1
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: first_name
      - name: last_name